# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ahmad Motamedi
title: Interested In Artificial Intelligence
email: ahmad.motamedi{gmail}
website: mtmdi.ir

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  mtmdi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ahmad_motamedi
linkedin_username: ahmad-motamedi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Ahmad Motamedi github
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-HMHEJ18QKN"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Being a geek and coding is one of the main pleasures of my life. I enjoy reading the code line by line. Interested in devising a better problem-solving method for challenging tasks. And learning new technologies and tools if the need arises.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: OS
        # link: tomaxco.com
        # link_text: boringcompany.com
        # sub_title: Chief Operating Officer
        # caption: Aug. 2017 - Mar. 2021
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Microsoft Windows
            - Debian
            - Ubuntu

      - layout: left
        title: DevOps
        # link: tomaxco.com
        # link_text: boringcompany.com
        # sub_title: Chief Operating Officer
        # caption: Aug. 2017 - Mar. 2021
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Git
            - Docker
            - VoIP
            - IIS
            - Apache 
            -Nginx   
            
      - layout: left
      title: Back-end
      description: | # this will include new lines to allow paragraphs
          - Flask
          - Django
          - REST API
          - pip
          - Virtual Environments
          - OOP

      - layout: left
      title: Data
      description: | # this will include new lines to allow paragraphs
          - Microsoft Access
          - Excel
          - SSIS
          - MSSQL
          - MySQL
          
      - layout: left
      title: Front-end
      description: | # this will include new lines to allow paragraphs
          - HTML
          - CSS

      - layout: left
      title: Programming
      description: | # this will include new lines to allow paragraphs
          - Python
          - C++
          - Bash
          - LaTeX
          
      - layout: left
      title: Programming
      description: | # this will include new lines to allow paragraphs
          - Clear Communication
          - Listening Skil
          - Self-control
          - Conflict Resolution
          - Empathy
          - Sense of Humor
          - Positive Attitude
    
        

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    
    content:
      - layout: left
        title: Tomax Co.
        link: tomaxco.com
        # link_text: boringcompany.com
        sub_title: Chief Operating Officer
        caption: Aug. 2017 - Mar. 2021
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Improving and updating the after-sales service process. (using specialized software and training the technicians)
            - Launching a happy call center to improve customer satisfaction
            - Responsibility for human resource recruitments. (From publishing recruitment advertisement to interviewing.)
            - Launching a shopping website(Prestashop, Magento).
            - Deploying VoIP technology to improve call quality and reduction in costs.
            - Implementing data center and web server from A to Z. From opting infrastructure to deploying applications. (FTTH, Windows server, IIS, MSSQL)
            - Executive manager at network projects.
            - Designing and rebranding corporate identity.

      - layout: left
        title: Isfahan Reebok
        link: www.reebokesfahan.com
        # link_text: boringcompany.com
        sub_title: Chief Operating Officer
        caption: Agu. 2016 - Aug. 2017
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Launching a shopping website(WordPress). improving website SEO to the third rank in Google.
            - Launching social media profile and improving its engagement (Instagram).

      - layout: left
        title: PooshTech
        link: www.reebokesfahan.com
        # link_text: boringcompany.com
        sub_title: Chief Executive Officer
        caption: Jan. 2016 - Jun. 2017
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Introducing and distributing wearable technology.
          - Importing smart bracelets and watches.

      # - layout: left
      #   title: University of Qom
      #   link: qom.ac.ir
      #   # link_text: boringcompany.com
      #   sub_title: Python Developer
      #   caption: Nov. 2010 - Jan. 2011
      #   # quote: >
      #     # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
      #   description: | # this will include new lines to allow paragraphs
      #     - Finding the shortest route in a graph with n$\times$n dimension based on Dijkstra's algorithm.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Islamic Azad University, Central Tehran Branch
        caption: 2020 present
        sub_title: MSc in Artificial Intelligence
        # quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
          # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          # I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: left
        title: University of Qom
        caption: Oct. 2008 - Sep. 2013
        sub_title: BSc in Physics
        description: |
          Study on Condensed matter physics: Physics of Ceramics and its application in industry.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
